services:
  autoencoder:
    build: .
    image: autoencoder
    tty: true
    stdin_open: true
    environment:
      - QT_X11_NO_MITSHM=1
      - HOST_USER=${USER}
      - NVIDIA_VISIBLE_DEVICES=all
    container_name: autoencoder_container
    # network_mode: "host"
    deploy:
      resources:
        limits:
          memory: 24gb
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ports:
      - "2224:22"